version: "3.8"
services:
  frontend-app:
    build: .
    container_name: frontend-inoive-converter
    ports:
      - "5000:5000"  # Expose port 80 di VPS dan port 3000 di container
    environment:
      - NODE_ENV=production
    restart: always